### ISSUE TITLE
Does not work with OSX < 10.14 any longer

### ISSUE THREAD

**Issue by drsassafras** [teras/Jubler#13]
The latest download 7alpha no longer works with OSX 10.13

![jubler](https://user-images.githubusercontent.com/18317850/71301680-64a3ff00-2370-11ea-9219-edc093508be2.jpeg)

**Comment by teras** [comment]
Indeed that’s true
I’ve checked in on OS X 10.12 and worked, but not on 10.13.

I’ll see what I can do.
Thanks for the bug report



--
Panayotis

**Comment by drsassafras** [comment]
Thanks for getting back so soon!

My first impression is that this might be a compile option that wasn't quite checked off properly. I have seen that issue before when apple updates its software and the process one normally uses changes a little. I know apple is getting rid of 32bit support right now, so compile options may be changing. Although that would not explain why it works in 10.12. In any case thanks for looking into it for me.

**Comment by teras** [comment]
Please tell me if this version found here works for you:

https://nx.yot.is/index.php/s/2kDKcG6WqMaYLJ8

**Comment by Nes-si** [comment]
@teras it works on 10.13.6.

**Comment by drsassafras** [comment]
Works just fine! thanks.
