### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by chka** [teras/Jubler#14]
Καλησπέρα,

Is it possible to have some build instructions for macos or at least an executable that runs on 10.13.6 (high sierra)? Not everyone has upgraded to the latest macos and the alpha release needs a bit of manual work to get compiled and then the generated jar doesn't start (something about input != null). It'll be great if we had instructions to create the .app file.

**Comment by teras** [comment]
On the main directory please issue the command `mvn install -Pdist-osx`.
Apart from that, I will upload a new MacOS version now.
