### ISSUE TITLE
Preview does not work on 7.0 alpha 3 on macOS

### ISSUE THREAD

**Issue by bouscram** [teras/Jubler#16]
The error message "FFDecode Library inactive..." is displayed with a demo image instead of the movie still.

Configuration : macOS 10.15.4
video format : h.264 mp4 file

**Comment by teras** [comment]
There's a fix underway. I'll post more about it soon.

**Comment by teras** [comment]
Please have a look at this version and report back if it works
https://github.com/teras/Jubler/releases/tag/v7.0.0-beta1

**Comment by bouscram** [comment]
It works now. :-)

**Comment by bouscram** [comment]
Fixed in 7.0 final
