### ISSUE TITLE
MPlayer works on Mac, only if it is pre-launched

### ISSUE THREAD

**Issue by tinca** [teras/Jubler#18]
Hi,
After upgrading 7 alpha to 7, my MPlayer Extended rev16 (1610) stopped to smoothly work. When trying to play movie from editor, Jubler suddenly exits leaving no message whatsoever. It keeps doing this as long as I separately launch MPlayer. I am not quite sure of the details, but pre-launching in some way MPlayer is certainly seems to be a prerequisite to be able to work later from editor.

**Comment by teras** [comment]
Let me try to understand.
You state that if MPlayer is already launched, then Jubler exits.
But then you say that pre-launching is a prerequisite to smoothly work?

Also, can you run Jubler from the command line?
The way to do this is as follows;
* Open `Terminal.app`
* Type `cd` and a space
* Drag & drop Jubler icon on the terminal. On the default installation of Jubler, you should see something like `cd /Applications/Jubler.app`
* Press [Enter].
* Type './Contents/MacOS/Jubler'

There you should see all debug information. Could you do this and send it back to see why it exits?

**Comment by tinca** [comment]
Sorry of possible wrong wording.
1. Jubler exits on trying to launch video from editor when no MPlayer was launched before. 
2.  Launching MPlayer before Jubler (pre-launching) helps.

I have tried it with AdoptOpenJDK 8 and 11. No difference.
Attached the file as you requested.
[Jubler.zip](https://github.com/teras/Jubler/files/4638522/Jubler.zip)

Thank you for looking into it.

**Comment by teras** [comment]
Hello, I mean not the file itself, but the output of the file when launched.
The file that you sent is the launcher :) 

There's no change between 7-alpha and 7 final version, in terms of MPlayer. Also JRE is embedded in latest versions, so there's no need to have JRE installed any more.

**Comment by tinca** [comment]
Ouch. This was so noob of me. Sorry...

Below log is for step 1:
`
[matroska,webm @ 0x7f954fa8e000] Estimating duration from bitrate, this may be inaccurate
/Applications/MPlayer OSX Extended.app/Contents/Resources/Binaries/mpextended.mpBinaries/Contents/MacOS/mplayer -noautosub -noquiet -nofs -slave -idle -ontop -utf8 -embeddedfonts -volstep 10 -sub /var/folders/c9/mgfx1b8j1156f04mgrtg2_p80000gp/T/jubler_15970610548266179005.ass -ss 00:01:33 -xy 1200 -geometry 30%10% -ass -font /Applications/Jubler.app/Contents/Java/lib/freesans.ttf -ass-font-scale 1.5 /Users/zkuti/Documents/sajat/Murdoch/S13-srt/E17/murdoch.mysteries.s13e17.720p.webrip.x264-cookiemonster.mkv # Port:50000 VideoFile:"/Users/zkuti/Documents/sajat/Murdoch/S13-srt/E17/murdoch.mysteries.s13e17.720p.webrip.x264-cookiemonster.mkv" SubtitleFile:"/var/folders/c9/mgfx1b8j1156f04mgrtg2_p80000gp/T/jubler_15970610548266179005.ass" At:00:01:33,000
MPlayer> MPlayer SVN-r38017-4.2.1 (C) 2000-2018 MPlayer Team
MPlayer! /Applications/Jubler.app/Contents/Java/lib/freesans.ttf doesn't look like a bitmap font description, ignoring.
MPlayer! Cannot load bitmap font '/Applications/Jubler.app/Contents/Java/lib/freesans.ttf'.
MPlayer> 
MPlayer> Playing /Users/zkuti/Documents/sajat/Murdoch/S13-srt/E17/murdoch.mysteries.s13e17.720p.webrip.x264-cookiemonster.mkv.
MPlayer> libavformat version 58.3.100 (internal)
MPlayer> libavformat file format detected.
MPlayer> [lavf] stream 0: video (h264), -vid 0
MPlayer> [lavf] stream 1: audio (ac3), -aid 0, -alang eng
MPlayer> VIDEO:  [H264]  1280x720  0bpp  23.976 fps    0.0 kbps ( 0.0 kbyte/s)
MPlayer> Opening video filter: [ass auto=1]
MPlayer> [ass] auto-open
MPlayer> [ass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.7.4 (COMPLEX)
MPlayer> ==========================================================================
MPlayer> Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
MPlayer> libavcodec version 58.9.100 (internal)
MPlayer> Selected video codec: [ffh264] vfm: ffmpeg (FFmpeg H.264)
MPlayer> ==========================================================================
MPlayer> Clip info:
MPlayer>  encoder: libebml v1.3.6 + libmatroska v1.4.9
MPlayer>  creation_time: 2020-02-25T01:11:48.000000Z
MPlayer> [ass] Added subtitle file: <memory> (2 styles, 760 events)
MPlayer> SUB: Added subtitle file (1): /var/folders/c9/mgfx1b8j1156f04mgrtg2_p80000gp/T/jubler_15970610548266179005.ass
MPlayer> ==========================================================================
MPlayer> Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
MPlayer! [ac3 @ 0x109b6f630]Channel layout '5.1(side)' with 6 channels does not match specified number of channels 2: ignoring specified channel layout
MPlayer> AUDIO: 48000 Hz, 2 ch, floatle, 384.0 kbit/12.50% (ratio: 48000->384000)
MPlayer> Selected audio codec: [ffac3] afm: ffmpeg (FFmpeg AC-3)
MPlayer> ==========================================================================
SIGILL: Illegal operation.
`
This is for step 2:

`[matroska,webm @ 0x7ffa0488c600] Estimating duration from bitrate, this may be inaccurate
/Applications/MPlayer OSX Extended.app/Contents/Resources/Binaries/mpextended.mpBinaries/Contents/MacOS/mplayer -noautosub -noquiet -nofs -slave -idle -ontop -utf8 -embeddedfonts -volstep 10 -sub /var/folders/c9/mgfx1b8j1156f04mgrtg2_p80000gp/T/jubler_16296947588437785538.ass -ss 00:00:35 -xy 1200 -geometry 30%10% -ass -font /Applications/Jubler.app/Contents/Java/lib/freesans.ttf -ass-font-scale 1.5 /Users/zkuti/Documents/sajat/Murdoch/S13-srt/E17/murdoch.mysteries.s13e17.720p.webrip.x264-cookiemonster.mkv # Port:50000 VideoFile:"/Users/zkuti/Documents/sajat/Murdoch/S13-srt/E17/murdoch.mysteries.s13e17.720p.webrip.x264-cookiemonster.mkv" SubtitleFile:"/var/folders/c9/mgfx1b8j1156f04mgrtg2_p80000gp/T/jubler_16296947588437785538.ass" At:00:00:35,000
MPlayer> MPlayer SVN-r38017-4.2.1 (C) 2000-2018 MPlayer Team
MPlayer! /Applications/Jubler.app/Contents/Java/lib/freesans.ttf doesn't look like a bitmap font description, ignoring.
MPlayer! Cannot load bitmap font '/Applications/Jubler.app/Contents/Java/lib/freesans.ttf'.
MPlayer> 
MPlayer> Playing /Users/zkuti/Documents/sajat/Murdoch/S13-srt/E17/murdoch.mysteries.s13e17.720p.webrip.x264-cookiemonster.mkv.
MPlayer> libavformat version 58.3.100 (internal)
MPlayer> libavformat file format detected.
MPlayer> [lavf] stream 0: video (h264), -vid 0
MPlayer> [lavf] stream 1: audio (ac3), -aid 0, -alang eng
MPlayer> VIDEO:  [H264]  1280x720  0bpp  23.976 fps    0.0 kbps ( 0.0 kbyte/s)
MPlayer> Opening video filter: [ass auto=1]
MPlayer> [ass] auto-open
MPlayer> [ass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.7.4 (COMPLEX)
MPlayer> ==========================================================================
MPlayer> Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
MPlayer> libavcodec version 58.9.100 (internal)
MPlayer> Selected video codec: [ffh264] vfm: ffmpeg (FFmpeg H.264)
MPlayer> ==========================================================================
MPlayer> Clip info:
MPlayer>  encoder: libebml v1.3.6 + libmatroska v1.4.9
MPlayer>  creation_time: 2020-02-25T01:11:48.000000Z
MPlayer> [ass] Added subtitle file: <memory> (2 styles, 760 events)
MPlayer> SUB: Added subtitle file (1): /var/folders/c9/mgfx1b8j1156f04mgrtg2_p80000gp/T/jubler_16296947588437785538.ass
MPlayer> ==========================================================================
MPlayer> Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
MPlayer! [ac3 @ 0x104ba5630]Channel layout '5.1(side)' with 6 channels does not match specified number of channels 2: ignoring specified channel layout
MPlayer> AUDIO: 48000 Hz, 2 ch, floatle, 384.0 kbit/12.50% (ratio: 48000->384000)
MPlayer> Selected audio codec: [ffac3] afm: ffmpeg (FFmpeg AC-3)
MPlayer> ==========================================================================
MPlayer> AO: [coreaudio] 48000Hz 2ch floatle (4 bytes per sample)
MPlayer> Starting playback...
MPlayer> Could not find matching colorspace - retrying with -vf scale...
MPlayer> Opening video filter: [scale]
MPlayer> Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
MPlayer> [swscaler @ 0x104bbdd00]bicubic scaler, from yuv420p to yuyv422 using MMXEXT
MPlayer> VO: [corevideo] 1280x720 => 1200x674 Packed YUY2 
MPlayer! -geometry must be in [WxH][[+-]X[+-]Y] | [X[%]:[Y[%]]] format, incorrect (30%10%)
MPlayer! [ASPECT] Warning: No suitable new res found!
MPlayer> [ass] fontselect: (Arial, 400, 0) -> /Applications/Jubler.app/Contents/Java/lib/freesans.ttf, 0, (none)
MPlayer! [ass] fontselect: Using default font: (Arial, 400, 0) -> /Applications/Jubler.app/Contents/Java/lib/freesans.ttf, 0, (none)
MPlayer! [ass] fontselect: Using default font: (Arial, 700, 0) -> /Applications/Jubler.app/Contents/Java/lib/freesans.ttf, 0, (none)
MPlayer> [ass] fontselect: (Arial, 700, 0) -> /Applications/Jubler.app/Contents/Java/lib/freesans.ttf, 0, (none)
MPlayer> ANS_volume=25.000000
MPlayer> 
MPlayer> Exiting... (Quit)
`

It is possible, that is has something to do with OS upgrade vs MPlayer (which is the latest available). Even if it were so, bit strange why pre-launch helps. Something could be initialized doing so, but not from launching first time from editor?

**Comment by teras** [comment]
Is it possible to add ` ``` ` before and after your pasted text?
You have to edit your post and do it like:

    ```
    ....your text...
    ```

**Comment by tinca** [comment]
Done.

**Comment by teras** [comment]
According to SO, this should be due to wrong version of MPlayer. Which might be an issue due to the latest "update" of macOS, not to run 32-bit code anymore.
Why this doesn't happen, when MPlayer is already run once, it probably has to do with some voodoo magic and/or a lot of luck.

Unfortunately there's no obvious solution for this problem and I don't think it could be solved.

**Comment by tinca** [comment]
Thank you for looking into it.

**Comment by teras** [comment]
I was able to reproduce the issue and I am working on it.

**Comment by teras** [comment]
Could you have a look if this version fixes this issue?
https://github.com/teras/Jubler/releases/tag/v7.0.1-beta2

**Comment by tinca** [comment]
Hi teras,

It seems to be fixed! Everything works as expected. Thank you!

**Comment by teras** [comment]
Could you try the new version?
The beta had some minor issues which I fixed it (but there were important to get things going).

I think I found a way to permanently fix it and thus I created a new release.

Thank you for the bug report

**Comment by tinca** [comment]
Installed 7.0.3. Opened a project of mine, tried out superficially, played video. Everything seems to be working.
