### ISSUE TITLE
Values of Name field are lost on save

### ISSUE THREAD

**Issue by josefk1100** [teras/Jubler#19]
Jubler doesn't give option to edit the `Name` field of dialogues. But if an ASS file which has values for `Name` field is opened in Jubler, those values are stripped when Jubler saves the file.

Steps to reproduce

1. Create subtitle file with `Name` field in another editor e.g. AegiSub [bob alice aegisub.ass.txt](https://github.com/teras/Jubler/files/4665055/bob.alice.aegisub.ass.txt)

<img width="788" alt="image" src="https://user-images.githubusercontent.com/65737389/82609415-238f6f80-9bda-11ea-8b3f-52ddeb9aa1c6.png">

2. Open the same file in Jubler. Modify and save it.
3. Open the file in the other editor. You'll now see that the values of `Name` field are lost.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/65737389/82609288-db704d00-9bd9-11ea-815c-e212e777b921.png">

 Even if Jubler doesn't support this field, it must be preserved when editing a file to ensure compatibility with other editors. The Name field is useful for working with dialogues.

**Comment by teras** [comment]
You are right :)

**Comment by teras** [comment]
Use this version.
https://github.com/teras/Jubler/releases/tag/v7.0.1-beta
It was an easy fix.

Since I changed the core part of the subtitle loading, please report back if ASS works as expected in general.

**Comment by josefk1100** [comment]
Checked with the above version and it works. Tested general stuff like adding, changing, and previewing subs and nothing seems broken.

@teras Thank you for fixing it so quickly 😊
