### ISSUE TITLE
7.03 java version

### ISSUE THREAD

**Issue by arliweng** [teras/Jubler#24]
the 7.03 class version 58 not 52, can't run with java 1.8
in project say java 1.8, but not, please check

**Comment by teras** [comment]
How do you run Jubler?
JRE is now embedded with Jubler to solve the millions of issues that Java runtime has

**Comment by teras** [comment]
After a second thought maybe you're right. The JRE could be whatever, but Jubler binaries itself maybe should stay Java 8 only.

**Comment by skaba** [comment]
Is there a Java8 version?

**Comment by teras** [comment]
If you compile yourself the version will be whatever JVM you have.
But right now, there's no such version.
Maybe I should go back to my old Mac and compile a new set of binaries using Java 8 instead and make it public.
I'll come back about it soon

**Comment by teras** [comment]
There is a new version of Jubler available, compiled with Java 8 now.
