### ISSUE TITLE
Add support for .sbv (Youtube subtitles)

### ISSUE THREAD

**Issue by dtmpsc** [teras/Jubler#27]
Youtube seems to have dropped the ability to download a video's subtitles as an srt and now only offers their own sbv. 
I've used Jubler to stripout the timecode info for creating a text script.
The workaround is to convert the sbv to srt here: https://gotranscript.com/subtitle-converter, then using Jubler.
Seems like an easily fix to add sbv support. 
Thanks for creating this useful program.

**Comment by teras** [comment]
if you can provide me with clear documentation of sdv, or even better have the regex that supports this format, I'll be happy to implement it.

**Comment by teras** [comment]
Next version of Jubler will support this format.
Stay tuned
