### ISSUE TITLE
Not playing full subtitle on Arch

### ISSUE THREAD

**Issue by roberttucker** [teras/Jubler#29]
When I click on "Play current subtitle" on Arch Linux, I do not hear the full subtitle (unless it is short). A .wav file is created in /tmp with the full audio for the subtitle. It is not deleted.  This is the case for all versions of Java.

On Fedora Linux, the subtitle is played, a .wav file is created in /tmp and then deleted after the subtitle has played. Nothing wrong, no problem.

No significant difference in terminal output on Arch or Fedora when running Jubler from terminal.

Any ideas, please? No response to my post on Arch forum.

**Comment by roberttucker** [comment]
Currently functioning correctly on Arch. No idea what the problem was (or might be again).

**Comment by teras** [comment]
Let's close this issue, right?
