### ISSUE TITLE
Localized GUI not working

### ISSUE THREAD

**Issue by pato-yapoq** [teras/Jubler#3]
Γέια σου,

using the generic binary distribution on Linux, when I run the tool, the localized gui was not working: `Unable to locate language cs`, although it is in the i18n folder.
I suspected that it was related to the paths, so I tried to move the jubler script file into the lib folder and modified the line to: `java -jar jubler.jar`, and now it works.
I am not sure why is this happening and whether you would do something with that, but I just wanted to let you know.

Ευχαριστώ

**Comment by teras** [comment]
Indeed there's an issue. Which operating system are you using to prepare a beta version for testing?

**Comment by pato-yapoq** [comment]
I am using openSUSE... Let me know in detail what you need, I am not sure what info you might need.

Euxaristó

**Comment by teras** [comment]
Fixed in latest version.
