### ISSUE TITLE
Importing SRT fil into Adobe Premiere

### ISSUE THREAD

**Issue by cyrilou1603** [teras/Jubler#38]
When I drag my Jubler srt file into Adobe Premiere, only two lines show up. However when I open the project in Jubler, I can see all lines of my project. is there a reason why?

I have made a screenshot of my problem to give you a better understanding!

https://github.com/teras/Jubler/assets/171566114/50867fc1-1339-4c54-b540-8a067fc3c536

**Comment by teras** [comment]
Please provide a sample of this file

**Comment by cyrilou1603** [comment]
Hi,

Sorry for the late reply. Unfortunately, I don't have the sample anymore...
________________________________
