### ISSUE TITLE
Hangs on File->Open

### ISSUE THREAD

**Issue by KoolKeith** [teras/Jubler#4]
Hello teras.
Jubler hangs (crashes) when I go File -> Open. I did uncheck the "JDK" option during install.

Windows 10, Oracle JDK 1.8.0_181

**Comment by KoolKeith** [comment]
Hi. Strangely it works now without the "manual" start you requested! I think it was caused due to my flaky network shares. This is not the only tool to crash on me because of this. Thank you.

**Comment by teras** [comment]
I'm happy that there isn't any real problem.

**Comment by KoolKeith** [comment]
Yes Sir, thank you.
