### ISSUE TITLE
MacOS - Flat WaveForm

### ISSUE THREAD

**Issue by hoangduytran** [teras/Jubler#40]
![Screenshot 2024-06-29 at 20 43 17](https://github.com/teras/Jubler/assets/149428565/eb3b79f5-0dbd-4771-a5e4-de3fd89803af)
Uploaded MP4 and at the 07:20,314, all the wave form display is FLAT. Do you know why?
Running on Ventura - 13.6.7 (22G720)

**Comment by hoangduytran** [comment]
Just update the log, that by removing the old cache file, reload the entire project and thus regenerating the cache file appeared to solve the problem. Waveform are fully generated. Don't know why do I have to do this though.

**Comment by teras** [comment]
Indeed that's the only way to fix this. Deleting the cache and let it regenerate. 

Why this happened I don't know though. Maybe something interrupted the process.

**Comment by teras** [comment]
I am going to close this issue for now
