### ISSUE TITLE
FFDecode library not active on Windows 64 bit version

### ISSUE THREAD

**Issue by AbdulHadiParsdorfer** [teras/Jubler#5]
Following problem shows up with the Windows 64 bit version: "FFDecode library not active. Using demo image." No Waveform preview is generated and no video preview. The Windows 32 bit version doesn't have this problem.

**Comment by teras** [comment]
The Java bit version should match the bit version of the application.
In other words, everything should be 32 or 64 bit (Java, App etc).

Is this the case with 64 bit?

**Comment by AbdulHadiParsdorfer** [comment]
Thank you. Jubler installed the Java version...?

**Comment by teras** [comment]
Oh I understand. Probably installed the 32 bit version, and you downloaded 64 version of Jubler.

Is it possible to download the 64 version of Java, uninstall 32 bit and check again?

**Comment by AbdulHadiParsdorfer** [comment]
I uninstalled Java and Jubler and installed the 32 bit version. That worked. I guess the Jubler installer package is maybe choosing the wrong Java version during the installation process. I don't know. Maybe you know. It happened on two computers.

**Comment by teras** [comment]
Fixed in latest alpha version
