### ISSUE TITLE
My video failed to import without explanation

### ISSUE THREAD

**Issue by Cassolotl** [teras/Jubler#7]
Reproduction steps:

1. Open Jubler for the first time.
2. Click *File > Open*
3. Select the video file (.mkv) I want to subtitle (which is not greyed out and is selectable) and click "open".
4. Nothing happens. No pop-up saying "incompatible file type, only the following types are allowed" or anything.

**OS:** Mac 10.14.4
**Jubler version:** 6.0.pre6

**Comment by teras** [comment]
Videos are not opened from Jubler, since they are not subtitle files.
Isn't there a filter to only enable subtitle files there?
