### ISSUE TITLE
JRELoadError

### ISSUE THREAD

**Issue by joethezombie** [teras/Jubler#8]
Jubler starts with an JRELoadError dialog.
I'm running macOS 10.14.6

```
java -version

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode, sharing)
```

Is there an issue with the AdoptOpenJDK implementation?

**Comment by teras** [comment]
I know, it's a bug of java launcher uner windows.
The only solution is to use another launcher or to embed the JRE instead.
I am actively working on the second solution.
If you are insterested I could provide a beta version of Jubler with embedded JRE to you.

**Comment by kuerb** [comment]
(I found this via google and want to share my workaround for others with the same issue:)
Opening Jubler.app/Contents/Java/jubler.jar directly seems to work for me. I'm not sure if that's what you meant by "using another launcher".

**Comment by teras** [comment]
The new version of Jubler has embedded JRE, exactly for this reason. This issue should be solved
