### ISSUE TITLE
HiDPI

### ISSUE THREAD

**Issue by roberttucker** [teras/Jubler#9]
Would it be possible to have an AppImage that starts Jubler using the sun.java2d.uiScale variable:
```
#!/bin/sh

cd `dirname $0`
java -Dsun.java2d.uiScale=2 -jar lib/jubler.jar
```
This works fine on OpenJDK 11 (but not OpenJDK 8) for the Generic Java version (but the FFDecode library is not active).

There seems to be an audio lag using xpra and run_scaled, and the only other alternative I've found on Gnome on Fedora 30 is to reduce my screen resolution to 1080 when using Jubler.

[Not sure this is an issue on KDE – I don't currently have it installed. Doesn't seem to be an issue on Gnome on Ubuntu.]

**Comment by roberttucker** [comment]
Actually, I think I've solved the problem. I dud:
`./Jubler-6.0.2.appimage --appimage-mount`
I then just copied libffdecode_64.so from the directory created in /tmp into ~/jubler/lib of the Generic Java version.

**Comment by teras** [comment]
I am in the process of distributing Jubler with embedded JRE, just to solve these kind of issues.

The second note, I didn't get it.
Was there a problem with the appimage and the embedded library?

**Comment by roberttucker** [comment]
I could only get Jubler to work with reasonably sized fonts etc while running my monitor at high resolution (4096x2160) using the Generic Java version and starting it with the command in my first post. But libffdecode_64.so doesn't seem to be included (in lib) in the Generic Java tarball, so I had to get it from the AppImage.

**Comment by teras** [comment]
Please check with the latest version of Jubler; Java 11 is known to properly work with HiDPI apps. 
If the problem persists, please reopen this issue. Thank you

**Comment by roberttucker** [comment]
On Gnome on Fedora 31 it's all still too tiny to work with.
On Gnome on Ubuntu 19.10 the fonts are a good size but the height of the lines is not sufficient to take them.
Both OpenJDK 11.

**Comment by teras** [comment]
Which JRE are you using? And where have you downloaded it from?

**Comment by roberttucker** [comment]
Fedora 31:

$ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment 18.9 (build 11.0.5+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.5+10, mixed mode, sharing


Ubuntu 19.10:

$ java -version
openjdk version "11.0.5-ea" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1, mixed mode, sharing)

**Comment by teras** [comment]
If you download the latest alpha version from here https://github.com/teras/Jubler/releases/tag/v7.0.0-alpha2 it is possible to pass -D parameters to the AppImage. Actually all -D parameters are passed to the JVM itself. Do you want to try to see if it works and report back?

**Comment by roberttucker** [comment]
Yes, it seems to work fine now on Fedora with:

$ ./Jubler-7.0.0-alpha2.appimage -Dsun.java2d.uiScale=2

Very many thanks.

**Comment by teras** [comment]
Thanks for the bug report
